### ISSUE TITLE
Add more sample html elements

### ISSUE THREAD

**Issue by himanshu-daga** [himanshu-daga/Webster#3]
add more samples for html elements using html and css.

**Comment by ankushgarg1998** [comment]
I'm working on img tag.

**Comment by hiroko** [comment]
Text Styling: Headers, Paragraphs, and Lists

**Comment by sperrye** [comment]
Table

**Comment by Lahirutech** [comment]
Shall I add about Lists !!

**Comment by cviddy** [comment]
Hey all, looking to help out. I was thinking about adding a section about html links and styling around them. Hoping to get something up this weekend.

**Comment by himanshu-daga** [comment]
Everyone thanks for contributing :smile: 
And keep up the good work. :+1: 
Also feel free to use these html patches in your own web projets.

**Comment by Sirius207** [comment]
Create FAB (Floating Action Button)!

**Comment by adlyloukil** [comment]
my first contribution, I just added the symbol elements 👍

**Comment by himanshu-daga** [comment]
Hello folks!
I am thinking of making a website to view all these samples live.
Give your reaction :+1:  or :-1:

**Comment by PrajapatiAnkit** [comment]
I am adding a form

**Comment by Lahirutech** [comment]
I will create an image gallery using CSS and HTML.

**Comment by himanshu-daga** [comment]
@Lahirutech 
Sure. You are welcome to add as you please!
Welcome to the community! :smile:

**Comment by vadikcorp** [comment]
create blog layout sample3
